backend:
  name: github
  repo: ObdachIos/Pitzlloch-Homepage
  branch: main
  base_url: https://pitzlloch-homepage.vercel.app
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: einstellungen
    label: "Einstellungen"
    files:
      - name: global
        label: "Kontakt Infos"
        file: "data/global.json"
        format: json
        fields:
          - { label: "Telefon", name: phone_display, widget: string }
          - { label: "E-Mail", name: email, widget: string }
          - { label: "Adresse Zeile 1", name: address1, widget: string }
